
yum -y install mailx
yum -y install mutt
yum -y install lynx
yum -y install wget
yum -y install curl
yum -y install bind-utils
yum -y install openssh-clients
yum -y install openssh-clients
yum -y install openssh-clients
yum -y install ftp
yum -y install telnet
yum -y install samba-clients
yum -y install tcpdump
yum -y install nmap
yum -y install freedts
yum -y install postgresql
yum -y install mysql
yum -y install openldap-clients
yum -y install tftp
yum -y install rpcbind
yum -y install firefox
yum -y install evolution
#yum -y install libreoffice-*
yum -y install nfs-utils
yum -y install tigervnc
yum -y install irssi
yum -y install net-snmp-utils
yum -y install nc
